CREATE TABLE audit_log (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_ts         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  db_user          VARCHAR2(128) NOT NULL,
  os_user          VARCHAR2(128),
  host             VARCHAR2(128),
  ip_addr          VARCHAR2(64),
  app_user         VARCHAR2(128),
  table_owner      VARCHAR2(128) NOT NULL,
  table_name       VARCHAR2(128) NOT NULL,
  pk_values        VARCHAR2(4000),
  operation        VARCHAR2(10) NOT NULL,
  changed_columns  VARCHAR2(4000),
  old_values       CLOB,
  new_values       CLOB
);
